version: '3'
services:
  web:
    build:
      context: ./server/nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./server/app:/var/www
      - ./server/nginx/conf.d:/etc/nginx/conf.d/
  app:
    build:
      context: ./server/app
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    env_file:
      - .env
    volumes:
      - ./server/app:/var/www

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'

